### match post test
POST http://localhost:8080/matches
Content-Type: application/json

{
    "user_id": "01KGF78ET1XDG1NHF08V66Q4ZB",
    "game_id": "01KGFESCKQX1EG9EJ964Y2019S"
}

### match delete test
DELETE http://localhost:8080/matches/01KGFESCKQX1EG9EJ964Y2019S
Content-Type: application/json

{
    "id": "01KH2X62JYSJFC0SVASVE043SG"
}