# @name login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "newuser1.test@example.com",
    "password": "password123"
}

### Update User
PUT http://localhost:8080/api/users/me
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
  "name": "관리자올름"
}

### Signup User
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "email": "newuser1.test@example.com",
    "password": "password123"
}

### Delete User
DELETE http://localhost:8080/api/users/me
Authorization: Bearer {{login.response.body.access_token}}
