app:
  env: "dev"
  port: 8080
  admin_path: "/admin"
  debug: true
  log_level: "debug"

db:
  host: "127.0.0.1"
  user: 
  password: 
  port: 5432
  dbname: "mydb"
  sslmode: "disable"

secure:
  cors_allow_origins:
    - "http://localhost:5173"
  jwt:
    private_key_base64: ""
    public_key_base64: ""
    access_expiration_min: 60
    refresh_expiration_day: 30
    cookie:
      secure: false
      http_only: true
      same_site: "Lax"
      domain: "localhost"

llm:
  openai_api_key: ""
  groq_api_key: ""

gcp:
  bucket_name: "ollm-assets-prod"
  project_id: "ollm-web"