version: '3.8'

services:
  frontend:
    image: ghcr.io/everyday-studio/ollm-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    container_name: llm-games-frontend
    ports:
      - "5173:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
