all: true                               # 모든 인터페이스에 대해 mock 자동 생성
with-expecter: true                     # Expect() 메서드 생성으로 호출 검증 지원
resolve-type-alias: false               # 타입 별칭 자동 해석 비활성화 (경고 방지)
issue-845-fix: true                     # Mockery의 #845 이슈 관련 경고 해결

packages:
  github.com/everyday-studio/ollm/internal/domain:
    config:
      dir: ./internal/domain/mocks
      filename: "Mock{{.InterfaceName}}.go"
      mockname: "{{.InterfaceName}}"
      outpkg: mocks