// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/everyday-studio/ollm/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// GameRepository is an autogenerated mock type for the GameRepository type
type GameRepository struct {
	mock.Mock
}

type GameRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *GameRepository) EXPECT() *GameRepository_Expecter {
	return &GameRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, game
func (_m *GameRepository) Create(ctx context.Context, game *domain.Game) (*domain.Game, error) {
	ret := _m.Called(ctx, game)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Game) (*domain.Game, error)); ok {
		return rf(ctx, game)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Game) *domain.Game); ok {
		r0 = rf(ctx, game)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Game)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Game) error); ok {
		r1 = rf(ctx, game)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GameRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type GameRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - game *domain.Game
func (_e *GameRepository_Expecter) Create(ctx interface{}, game interface{}) *GameRepository_Create_Call {
	return &GameRepository_Create_Call{Call: _e.mock.On("Create", ctx, game)}
}

func (_c *GameRepository_Create_Call) Run(run func(ctx context.Context, game *domain.Game)) *GameRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Game))
	})
	return _c
}

func (_c *GameRepository_Create_Call) Return(_a0 *domain.Game, _a1 error) *GameRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GameRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Game) (*domain.Game, error)) *GameRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *GameRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GameRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type GameRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *GameRepository_Expecter) Delete(ctx interface{}, id interface{}) *GameRepository_Delete_Call {
	return &GameRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *GameRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *GameRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *GameRepository_Delete_Call) Return(_a0 error) *GameRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GameRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *GameRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *GameRepository) GetAll(ctx context.Context) ([]domain.Game, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Game, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Game); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Game)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GameRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type GameRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *GameRepository_Expecter) GetAll(ctx interface{}) *GameRepository_GetAll_Call {
	return &GameRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *GameRepository_GetAll_Call) Run(run func(ctx context.Context)) *GameRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *GameRepository_GetAll_Call) Return(_a0 []domain.Game, _a1 error) *GameRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GameRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]domain.Game, error)) *GameRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *GameRepository) GetByID(ctx context.Context, id string) (*domain.Game, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Game, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Game); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Game)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GameRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type GameRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *GameRepository_Expecter) GetByID(ctx interface{}, id interface{}) *GameRepository_GetByID_Call {
	return &GameRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *GameRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *GameRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *GameRepository_GetByID_Call) Return(_a0 *domain.Game, _a1 error) *GameRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GameRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*domain.Game, error)) *GameRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, game
func (_m *GameRepository) Update(ctx context.Context, game *domain.Game) (*domain.Game, error) {
	ret := _m.Called(ctx, game)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Game) (*domain.Game, error)); ok {
		return rf(ctx, game)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Game) *domain.Game); ok {
		r0 = rf(ctx, game)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Game)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Game) error); ok {
		r1 = rf(ctx, game)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GameRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type GameRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - game *domain.Game
func (_e *GameRepository_Expecter) Update(ctx interface{}, game interface{}) *GameRepository_Update_Call {
	return &GameRepository_Update_Call{Call: _e.mock.On("Update", ctx, game)}
}

func (_c *GameRepository_Update_Call) Run(run func(ctx context.Context, game *domain.Game)) *GameRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Game))
	})
	return _c
}

func (_c *GameRepository_Update_Call) Return(_a0 *domain.Game, _a1 error) *GameRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GameRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Game) (*domain.Game, error)) *GameRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewGameRepository creates a new instance of GameRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGameRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GameRepository {
	mock := &GameRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
