// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/everyday-studio/ollm/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MessageRepository is an autogenerated mock type for the MessageRepository type
type MessageRepository struct {
	mock.Mock
}

type MessageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageRepository) EXPECT() *MessageRepository_Expecter {
	return &MessageRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, message
func (_m *MessageRepository) Create(ctx context.Context, message *domain.Message) (*domain.Message, error) {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Message) (*domain.Message, error)); ok {
		return rf(ctx, message)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Message) *domain.Message); ok {
		r0 = rf(ctx, message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Message) error); ok {
		r1 = rf(ctx, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MessageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - message *domain.Message
func (_e *MessageRepository_Expecter) Create(ctx interface{}, message interface{}) *MessageRepository_Create_Call {
	return &MessageRepository_Create_Call{Call: _e.mock.On("Create", ctx, message)}
}

func (_c *MessageRepository_Create_Call) Run(run func(ctx context.Context, message *domain.Message)) *MessageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Message))
	})
	return _c
}

func (_c *MessageRepository_Create_Call) Return(_a0 *domain.Message, _a1 error) *MessageRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Message) (*domain.Message, error)) *MessageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MessageRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MessageRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MessageRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MessageRepository_Expecter) Delete(ctx interface{}, id interface{}) *MessageRepository_Delete_Call {
	return &MessageRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MessageRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MessageRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MessageRepository_Delete_Call) Return(_a0 error) *MessageRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MessageRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MessageRepository) GetByID(ctx context.Context, id string) (*domain.Message, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Message, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Message); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MessageRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MessageRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MessageRepository_GetByID_Call {
	return &MessageRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MessageRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MessageRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MessageRepository_GetByID_Call) Return(_a0 *domain.Message, _a1 error) *MessageRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*domain.Message, error)) *MessageRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByMatchID provides a mock function with given fields: ctx, matchID
func (_m *MessageRepository) GetByMatchID(ctx context.Context, matchID string) ([]domain.Message, error) {
	ret := _m.Called(ctx, matchID)

	if len(ret) == 0 {
		panic("no return value specified for GetByMatchID")
	}

	var r0 []domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Message, error)); ok {
		return rf(ctx, matchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Message); ok {
		r0 = rf(ctx, matchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, matchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageRepository_GetByMatchID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByMatchID'
type MessageRepository_GetByMatchID_Call struct {
	*mock.Call
}

// GetByMatchID is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID string
func (_e *MessageRepository_Expecter) GetByMatchID(ctx interface{}, matchID interface{}) *MessageRepository_GetByMatchID_Call {
	return &MessageRepository_GetByMatchID_Call{Call: _e.mock.On("GetByMatchID", ctx, matchID)}
}

func (_c *MessageRepository_GetByMatchID_Call) Run(run func(ctx context.Context, matchID string)) *MessageRepository_GetByMatchID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MessageRepository_GetByMatchID_Call) Return(_a0 []domain.Message, _a1 error) *MessageRepository_GetByMatchID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageRepository_GetByMatchID_Call) RunAndReturn(run func(context.Context, string) ([]domain.Message, error)) *MessageRepository_GetByMatchID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, message
func (_m *MessageRepository) Update(ctx context.Context, message *domain.Message) (*domain.Message, error) {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Message) (*domain.Message, error)); ok {
		return rf(ctx, message)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Message) *domain.Message); ok {
		r0 = rf(ctx, message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Message) error); ok {
		r1 = rf(ctx, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MessageRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - message *domain.Message
func (_e *MessageRepository_Expecter) Update(ctx interface{}, message interface{}) *MessageRepository_Update_Call {
	return &MessageRepository_Update_Call{Call: _e.mock.On("Update", ctx, message)}
}

func (_c *MessageRepository_Update_Call) Run(run func(ctx context.Context, message *domain.Message)) *MessageRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Message))
	})
	return _c
}

func (_c *MessageRepository_Update_Call) Return(_a0 *domain.Message, _a1 error) *MessageRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Message) (*domain.Message, error)) *MessageRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageRepository creates a new instance of MessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageRepository {
	mock := &MessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
