// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/everyday-studio/ollm/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// AuthUsecase is an autogenerated mock type for the AuthUsecase type
type AuthUsecase struct {
	mock.Mock
}

type AuthUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthUsecase) EXPECT() *AuthUsecase_Expecter {
	return &AuthUsecase_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *AuthUsecase) Login(ctx context.Context, email string, password string) (*domain.LoginResponse, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *domain.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.LoginResponse, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.LoginResponse); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthUsecase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthUsecase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *AuthUsecase_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *AuthUsecase_Login_Call {
	return &AuthUsecase_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *AuthUsecase_Login_Call) Run(run func(ctx context.Context, email string, password string)) *AuthUsecase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AuthUsecase_Login_Call) Return(_a0 *domain.LoginResponse, _a1 error) *AuthUsecase_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthUsecase_Login_Call) RunAndReturn(run func(context.Context, string, string) (*domain.LoginResponse, error)) *AuthUsecase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, userID
func (_m *AuthUsecase) Logout(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthUsecase_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AuthUsecase_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *AuthUsecase_Expecter) Logout(ctx interface{}, userID interface{}) *AuthUsecase_Logout_Call {
	return &AuthUsecase_Logout_Call{Call: _e.mock.On("Logout", ctx, userID)}
}

func (_c *AuthUsecase_Logout_Call) Run(run func(ctx context.Context, userID int64)) *AuthUsecase_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *AuthUsecase_Logout_Call) Return(_a0 error) *AuthUsecase_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthUsecase_Logout_Call) RunAndReturn(run func(context.Context, int64) error) *AuthUsecase_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: ctx, refreshToken
func (_m *AuthUsecase) RefreshToken(ctx context.Context, refreshToken string) (*domain.LoginResponse, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *domain.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.LoginResponse, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.LoginResponse); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthUsecase_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type AuthUsecase_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *AuthUsecase_Expecter) RefreshToken(ctx interface{}, refreshToken interface{}) *AuthUsecase_RefreshToken_Call {
	return &AuthUsecase_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken)}
}

func (_c *AuthUsecase_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *AuthUsecase_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthUsecase_RefreshToken_Call) Return(_a0 *domain.LoginResponse, _a1 error) *AuthUsecase_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthUsecase_RefreshToken_Call) RunAndReturn(run func(context.Context, string) (*domain.LoginResponse, error)) *AuthUsecase_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// SignUpUser provides a mock function with given fields: ctx, user
func (_m *AuthUsecase) SignUpUser(ctx context.Context, user *domain.User) (*domain.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for SignUpUser")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) (*domain.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) *domain.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthUsecase_SignUpUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUpUser'
type AuthUsecase_SignUpUser_Call struct {
	*mock.Call
}

// SignUpUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *AuthUsecase_Expecter) SignUpUser(ctx interface{}, user interface{}) *AuthUsecase_SignUpUser_Call {
	return &AuthUsecase_SignUpUser_Call{Call: _e.mock.On("SignUpUser", ctx, user)}
}

func (_c *AuthUsecase_SignUpUser_Call) Run(run func(ctx context.Context, user *domain.User)) *AuthUsecase_SignUpUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User))
	})
	return _c
}

func (_c *AuthUsecase_SignUpUser_Call) Return(_a0 *domain.User, _a1 error) *AuthUsecase_SignUpUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthUsecase_SignUpUser_Call) RunAndReturn(run func(context.Context, *domain.User) (*domain.User, error)) *AuthUsecase_SignUpUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthUsecase creates a new instance of AuthUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthUsecase {
	mock := &AuthUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
