// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// StorageService is an autogenerated mock type for the StorageService type
type StorageService struct {
	mock.Mock
}

type StorageService_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageService) EXPECT() *StorageService_Expecter {
	return &StorageService_Expecter{mock: &_m.Mock}
}

// UploadImage provides a mock function with given fields: ctx, file, objectName, contentType
func (_m *StorageService) UploadImage(ctx context.Context, file io.Reader, objectName string, contentType string) (string, error) {
	ret := _m.Called(ctx, file, objectName, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UploadImage")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string, string) (string, error)); ok {
		return rf(ctx, file, objectName, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string, string) string); ok {
		r0 = rf(ctx, file, objectName, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.Reader, string, string) error); ok {
		r1 = rf(ctx, file, objectName, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageService_UploadImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadImage'
type StorageService_UploadImage_Call struct {
	*mock.Call
}

// UploadImage is a helper method to define mock.On call
//   - ctx context.Context
//   - file io.Reader
//   - objectName string
//   - contentType string
func (_e *StorageService_Expecter) UploadImage(ctx interface{}, file interface{}, objectName interface{}, contentType interface{}) *StorageService_UploadImage_Call {
	return &StorageService_UploadImage_Call{Call: _e.mock.On("UploadImage", ctx, file, objectName, contentType)}
}

func (_c *StorageService_UploadImage_Call) Run(run func(ctx context.Context, file io.Reader, objectName string, contentType string)) *StorageService_UploadImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *StorageService_UploadImage_Call) Return(_a0 string, _a1 error) *StorageService_UploadImage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageService_UploadImage_Call) RunAndReturn(run func(context.Context, io.Reader, string, string) (string, error)) *StorageService_UploadImage_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorageService creates a new instance of StorageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageService {
	mock := &StorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
