// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/everyday-studio/ollm/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MessageUseCase is an autogenerated mock type for the MessageUseCase type
type MessageUseCase struct {
	mock.Mock
}

type MessageUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageUseCase) EXPECT() *MessageUseCase_Expecter {
	return &MessageUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, matchID, userID, req
func (_m *MessageUseCase) Create(ctx context.Context, matchID string, userID string, req *domain.CreateMessageRequest) (*domain.Message, error) {
	ret := _m.Called(ctx, matchID, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *domain.CreateMessageRequest) (*domain.Message, error)); ok {
		return rf(ctx, matchID, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *domain.CreateMessageRequest) *domain.Message); ok {
		r0 = rf(ctx, matchID, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *domain.CreateMessageRequest) error); ok {
		r1 = rf(ctx, matchID, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MessageUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID string
//   - userID string
//   - req *domain.CreateMessageRequest
func (_e *MessageUseCase_Expecter) Create(ctx interface{}, matchID interface{}, userID interface{}, req interface{}) *MessageUseCase_Create_Call {
	return &MessageUseCase_Create_Call{Call: _e.mock.On("Create", ctx, matchID, userID, req)}
}

func (_c *MessageUseCase_Create_Call) Run(run func(ctx context.Context, matchID string, userID string, req *domain.CreateMessageRequest)) *MessageUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*domain.CreateMessageRequest))
	})
	return _c
}

func (_c *MessageUseCase_Create_Call) Return(_a0 *domain.Message, _a1 error) *MessageUseCase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageUseCase_Create_Call) RunAndReturn(run func(context.Context, string, string, *domain.CreateMessageRequest) (*domain.Message, error)) *MessageUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MessageUseCase) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MessageUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MessageUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MessageUseCase_Expecter) Delete(ctx interface{}, id interface{}) *MessageUseCase_Delete_Call {
	return &MessageUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MessageUseCase_Delete_Call) Run(run func(ctx context.Context, id string)) *MessageUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MessageUseCase_Delete_Call) Return(_a0 error) *MessageUseCase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageUseCase_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MessageUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MessageUseCase) GetByID(ctx context.Context, id string) (*domain.Message, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Message, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Message); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageUseCase_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MessageUseCase_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MessageUseCase_Expecter) GetByID(ctx interface{}, id interface{}) *MessageUseCase_GetByID_Call {
	return &MessageUseCase_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MessageUseCase_GetByID_Call) Run(run func(ctx context.Context, id string)) *MessageUseCase_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MessageUseCase_GetByID_Call) Return(_a0 *domain.Message, _a1 error) *MessageUseCase_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageUseCase_GetByID_Call) RunAndReturn(run func(context.Context, string) (*domain.Message, error)) *MessageUseCase_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByMatchID provides a mock function with given fields: ctx, matchID, userID
func (_m *MessageUseCase) GetByMatchID(ctx context.Context, matchID string, userID string) ([]domain.Message, error) {
	ret := _m.Called(ctx, matchID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByMatchID")
	}

	var r0 []domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]domain.Message, error)); ok {
		return rf(ctx, matchID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []domain.Message); ok {
		r0 = rf(ctx, matchID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, matchID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageUseCase_GetByMatchID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByMatchID'
type MessageUseCase_GetByMatchID_Call struct {
	*mock.Call
}

// GetByMatchID is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID string
//   - userID string
func (_e *MessageUseCase_Expecter) GetByMatchID(ctx interface{}, matchID interface{}, userID interface{}) *MessageUseCase_GetByMatchID_Call {
	return &MessageUseCase_GetByMatchID_Call{Call: _e.mock.On("GetByMatchID", ctx, matchID, userID)}
}

func (_c *MessageUseCase_GetByMatchID_Call) Run(run func(ctx context.Context, matchID string, userID string)) *MessageUseCase_GetByMatchID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MessageUseCase_GetByMatchID_Call) Return(_a0 []domain.Message, _a1 error) *MessageUseCase_GetByMatchID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageUseCase_GetByMatchID_Call) RunAndReturn(run func(context.Context, string, string) ([]domain.Message, error)) *MessageUseCase_GetByMatchID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageUseCase creates a new instance of MessageUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageUseCase {
	mock := &MessageUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
