// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/everyday-studio/ollm/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// UserUseCase is an autogenerated mock type for the UserUseCase type
type UserUseCase struct {
	mock.Mock
}

type UserUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *UserUseCase) EXPECT() *UserUseCase_Expecter {
	return &UserUseCase_Expecter{mock: &_m.Mock}
}

// CountAll provides a mock function with given fields: ctx
func (_m *UserUseCase) CountAll(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountAll")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserUseCase_CountAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountAll'
type UserUseCase_CountAll_Call struct {
	*mock.Call
}

// CountAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserUseCase_Expecter) CountAll(ctx interface{}) *UserUseCase_CountAll_Call {
	return &UserUseCase_CountAll_Call{Call: _e.mock.On("CountAll", ctx)}
}

func (_c *UserUseCase_CountAll_Call) Run(run func(ctx context.Context)) *UserUseCase_CountAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UserUseCase_CountAll_Call) Return(_a0 int, _a1 error) *UserUseCase_CountAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserUseCase_CountAll_Call) RunAndReturn(run func(context.Context) (int, error)) *UserUseCase_CountAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UserUseCase) GetByID(ctx context.Context, id string) (*domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserUseCase_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserUseCase_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserUseCase_Expecter) GetByID(ctx interface{}, id interface{}) *UserUseCase_GetByID_Call {
	return &UserUseCase_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *UserUseCase_GetByID_Call) Run(run func(ctx context.Context, id string)) *UserUseCase_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserUseCase_GetByID_Call) Return(_a0 *domain.User, _a1 error) *UserUseCase_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserUseCase_GetByID_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *UserUseCase_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPaginated provides a mock function with given fields: ctx, page, limit
func (_m *UserUseCase) GetPaginated(ctx context.Context, page int, limit int) (*domain.PaginatedData[domain.User], error) {
	ret := _m.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPaginated")
	}

	var r0 *domain.PaginatedData[domain.User]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*domain.PaginatedData[domain.User], error)); ok {
		return rf(ctx, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *domain.PaginatedData[domain.User]); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaginatedData[domain.User])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserUseCase_GetPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPaginated'
type UserUseCase_GetPaginated_Call struct {
	*mock.Call
}

// GetPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
func (_e *UserUseCase_Expecter) GetPaginated(ctx interface{}, page interface{}, limit interface{}) *UserUseCase_GetPaginated_Call {
	return &UserUseCase_GetPaginated_Call{Call: _e.mock.On("GetPaginated", ctx, page, limit)}
}

func (_c *UserUseCase_GetPaginated_Call) Run(run func(ctx context.Context, page int, limit int)) *UserUseCase_GetPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *UserUseCase_GetPaginated_Call) Return(_a0 *domain.PaginatedData[domain.User], _a1 error) *UserUseCase_GetPaginated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserUseCase_GetPaginated_Call) RunAndReturn(run func(context.Context, int, int) (*domain.PaginatedData[domain.User], error)) *UserUseCase_GetPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNickname provides a mock function with given fields: ctx, id, name
func (_m *UserUseCase) UpdateNickname(ctx context.Context, id string, name string) (*domain.User, error) {
	ret := _m.Called(ctx, id, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNickname")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return rf(ctx, id, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, id, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserUseCase_UpdateNickname_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNickname'
type UserUseCase_UpdateNickname_Call struct {
	*mock.Call
}

// UpdateNickname is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - name string
func (_e *UserUseCase_Expecter) UpdateNickname(ctx interface{}, id interface{}, name interface{}) *UserUseCase_UpdateNickname_Call {
	return &UserUseCase_UpdateNickname_Call{Call: _e.mock.On("UpdateNickname", ctx, id, name)}
}

func (_c *UserUseCase_UpdateNickname_Call) Run(run func(ctx context.Context, id string, name string)) *UserUseCase_UpdateNickname_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserUseCase_UpdateNickname_Call) Return(_a0 *domain.User, _a1 error) *UserUseCase_UpdateNickname_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserUseCase_UpdateNickname_Call) RunAndReturn(run func(context.Context, string, string) (*domain.User, error)) *UserUseCase_UpdateNickname_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserUseCase creates a new instance of UserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserUseCase {
	mock := &UserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
