// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/everyday-studio/ollm/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// LeaderboardUseCase is an autogenerated mock type for the LeaderboardUseCase type
type LeaderboardUseCase struct {
	mock.Mock
}

type LeaderboardUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *LeaderboardUseCase) EXPECT() *LeaderboardUseCase_Expecter {
	return &LeaderboardUseCase_Expecter{mock: &_m.Mock}
}

// GetLeaderboard provides a mock function with given fields: ctx, gameID, limit
func (_m *LeaderboardUseCase) GetLeaderboard(ctx context.Context, gameID string, limit int) ([]domain.LeaderboardEntry, error) {
	ret := _m.Called(ctx, gameID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaderboard")
	}

	var r0 []domain.LeaderboardEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]domain.LeaderboardEntry, error)); ok {
		return rf(ctx, gameID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []domain.LeaderboardEntry); ok {
		r0 = rf(ctx, gameID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.LeaderboardEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, gameID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LeaderboardUseCase_GetLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaderboard'
type LeaderboardUseCase_GetLeaderboard_Call struct {
	*mock.Call
}

// GetLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - gameID string
//   - limit int
func (_e *LeaderboardUseCase_Expecter) GetLeaderboard(ctx interface{}, gameID interface{}, limit interface{}) *LeaderboardUseCase_GetLeaderboard_Call {
	return &LeaderboardUseCase_GetLeaderboard_Call{Call: _e.mock.On("GetLeaderboard", ctx, gameID, limit)}
}

func (_c *LeaderboardUseCase_GetLeaderboard_Call) Run(run func(ctx context.Context, gameID string, limit int)) *LeaderboardUseCase_GetLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *LeaderboardUseCase_GetLeaderboard_Call) Return(_a0 []domain.LeaderboardEntry, _a1 error) *LeaderboardUseCase_GetLeaderboard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LeaderboardUseCase_GetLeaderboard_Call) RunAndReturn(run func(context.Context, string, int) ([]domain.LeaderboardEntry, error)) *LeaderboardUseCase_GetLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// NewLeaderboardUseCase creates a new instance of LeaderboardUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLeaderboardUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *LeaderboardUseCase {
	mock := &LeaderboardUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
