// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/everyday-studio/ollm/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MatchRepository is an autogenerated mock type for the MatchRepository type
type MatchRepository struct {
	mock.Mock
}

type MatchRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MatchRepository) EXPECT() *MatchRepository_Expecter {
	return &MatchRepository_Expecter{mock: &_m.Mock}
}

// CountByUserIDAndStatus provides a mock function with given fields: ctx, userID, status
func (_m *MatchRepository) CountByUserIDAndStatus(ctx context.Context, userID string, status domain.MatchStatus) (int, error) {
	ret := _m.Called(ctx, userID, status)

	if len(ret) == 0 {
		panic("no return value specified for CountByUserIDAndStatus")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.MatchStatus) (int, error)); ok {
		return rf(ctx, userID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.MatchStatus) int); ok {
		r0 = rf(ctx, userID, status)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.MatchStatus) error); ok {
		r1 = rf(ctx, userID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MatchRepository_CountByUserIDAndStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByUserIDAndStatus'
type MatchRepository_CountByUserIDAndStatus_Call struct {
	*mock.Call
}

// CountByUserIDAndStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - status domain.MatchStatus
func (_e *MatchRepository_Expecter) CountByUserIDAndStatus(ctx interface{}, userID interface{}, status interface{}) *MatchRepository_CountByUserIDAndStatus_Call {
	return &MatchRepository_CountByUserIDAndStatus_Call{Call: _e.mock.On("CountByUserIDAndStatus", ctx, userID, status)}
}

func (_c *MatchRepository_CountByUserIDAndStatus_Call) Run(run func(ctx context.Context, userID string, status domain.MatchStatus)) *MatchRepository_CountByUserIDAndStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.MatchStatus))
	})
	return _c
}

func (_c *MatchRepository_CountByUserIDAndStatus_Call) Return(_a0 int, _a1 error) *MatchRepository_CountByUserIDAndStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MatchRepository_CountByUserIDAndStatus_Call) RunAndReturn(run func(context.Context, string, domain.MatchStatus) (int, error)) *MatchRepository_CountByUserIDAndStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, match
func (_m *MatchRepository) Create(ctx context.Context, match *domain.Match) (*domain.Match, error) {
	ret := _m.Called(ctx, match)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Match) (*domain.Match, error)); ok {
		return rf(ctx, match)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Match) *domain.Match); ok {
		r0 = rf(ctx, match)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Match) error); ok {
		r1 = rf(ctx, match)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MatchRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MatchRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - match *domain.Match
func (_e *MatchRepository_Expecter) Create(ctx interface{}, match interface{}) *MatchRepository_Create_Call {
	return &MatchRepository_Create_Call{Call: _e.mock.On("Create", ctx, match)}
}

func (_c *MatchRepository_Create_Call) Run(run func(ctx context.Context, match *domain.Match)) *MatchRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Match))
	})
	return _c
}

func (_c *MatchRepository_Create_Call) Return(_a0 *domain.Match, _a1 error) *MatchRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MatchRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Match) (*domain.Match, error)) *MatchRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MatchRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MatchRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MatchRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MatchRepository_Expecter) Delete(ctx interface{}, id interface{}) *MatchRepository_Delete_Call {
	return &MatchRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MatchRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MatchRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MatchRepository_Delete_Call) Return(_a0 error) *MatchRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MatchRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MatchRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MatchRepository) GetByID(ctx context.Context, id string) (*domain.Match, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Match, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Match); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MatchRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MatchRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MatchRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MatchRepository_GetByID_Call {
	return &MatchRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MatchRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MatchRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MatchRepository_GetByID_Call) Return(_a0 *domain.Match, _a1 error) *MatchRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MatchRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*domain.Match, error)) *MatchRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *MatchRepository) GetByUserID(ctx context.Context, userID string) ([]domain.Match, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []domain.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Match, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Match); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MatchRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MatchRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MatchRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MatchRepository_GetByUserID_Call {
	return &MatchRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MatchRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID string)) *MatchRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MatchRepository_GetByUserID_Call) Return(_a0 []domain.Match, _a1 error) *MatchRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MatchRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, string) ([]domain.Match, error)) *MatchRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserIDAndGameID provides a mock function with given fields: ctx, userID, gameID
func (_m *MatchRepository) GetByUserIDAndGameID(ctx context.Context, userID string, gameID string) ([]domain.Match, error) {
	ret := _m.Called(ctx, userID, gameID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserIDAndGameID")
	}

	var r0 []domain.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]domain.Match, error)); ok {
		return rf(ctx, userID, gameID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []domain.Match); ok {
		r0 = rf(ctx, userID, gameID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, gameID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MatchRepository_GetByUserIDAndGameID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserIDAndGameID'
type MatchRepository_GetByUserIDAndGameID_Call struct {
	*mock.Call
}

// GetByUserIDAndGameID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - gameID string
func (_e *MatchRepository_Expecter) GetByUserIDAndGameID(ctx interface{}, userID interface{}, gameID interface{}) *MatchRepository_GetByUserIDAndGameID_Call {
	return &MatchRepository_GetByUserIDAndGameID_Call{Call: _e.mock.On("GetByUserIDAndGameID", ctx, userID, gameID)}
}

func (_c *MatchRepository_GetByUserIDAndGameID_Call) Run(run func(ctx context.Context, userID string, gameID string)) *MatchRepository_GetByUserIDAndGameID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MatchRepository_GetByUserIDAndGameID_Call) Return(_a0 []domain.Match, _a1 error) *MatchRepository_GetByUserIDAndGameID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MatchRepository_GetByUserIDAndGameID_Call) RunAndReturn(run func(context.Context, string, string) ([]domain.Match, error)) *MatchRepository_GetByUserIDAndGameID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, match
func (_m *MatchRepository) Update(ctx context.Context, match *domain.Match) (*domain.Match, error) {
	ret := _m.Called(ctx, match)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Match) (*domain.Match, error)); ok {
		return rf(ctx, match)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Match) *domain.Match); ok {
		r0 = rf(ctx, match)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Match) error); ok {
		r1 = rf(ctx, match)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MatchRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MatchRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - match *domain.Match
func (_e *MatchRepository_Expecter) Update(ctx interface{}, match interface{}) *MatchRepository_Update_Call {
	return &MatchRepository_Update_Call{Call: _e.mock.On("Update", ctx, match)}
}

func (_c *MatchRepository_Update_Call) Run(run func(ctx context.Context, match *domain.Match)) *MatchRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Match))
	})
	return _c
}

func (_c *MatchRepository_Update_Call) Return(_a0 *domain.Match, _a1 error) *MatchRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MatchRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Match) (*domain.Match, error)) *MatchRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMatchRepository creates a new instance of MatchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMatchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MatchRepository {
	mock := &MatchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
