// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/everyday-studio/ollm/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MatchRepository is an autogenerated mock type for the MatchRepository type
type MatchRepository struct {
	mock.Mock
}

type MatchRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MatchRepository) EXPECT() *MatchRepository_Expecter {
	return &MatchRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, match
func (_m *MatchRepository) Create(ctx context.Context, match *domain.Match) (*domain.Match, error) {
	ret := _m.Called(ctx, match)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Match) (*domain.Match, error)); ok {
		return rf(ctx, match)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Match) *domain.Match); ok {
		r0 = rf(ctx, match)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Match) error); ok {
		r1 = rf(ctx, match)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MatchRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MatchRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - match *domain.Match
func (_e *MatchRepository_Expecter) Create(ctx interface{}, match interface{}) *MatchRepository_Create_Call {
	return &MatchRepository_Create_Call{Call: _e.mock.On("Create", ctx, match)}
}

func (_c *MatchRepository_Create_Call) Run(run func(ctx context.Context, match *domain.Match)) *MatchRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Match))
	})
	return _c
}

func (_c *MatchRepository_Create_Call) Return(_a0 *domain.Match, _a1 error) *MatchRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MatchRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Match) (*domain.Match, error)) *MatchRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MatchRepository) GetByID(ctx context.Context, id string) (*domain.Match, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Match, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Match); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MatchRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MatchRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MatchRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MatchRepository_GetByID_Call {
	return &MatchRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MatchRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MatchRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MatchRepository_GetByID_Call) Return(_a0 *domain.Match, _a1 error) *MatchRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MatchRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*domain.Match, error)) *MatchRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *MatchRepository) GetByUserID(ctx context.Context, userID string) ([]domain.Match, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []domain.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Match, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Match); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MatchRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MatchRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MatchRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MatchRepository_GetByUserID_Call {
	return &MatchRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MatchRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID string)) *MatchRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MatchRepository_GetByUserID_Call) Return(_a0 []domain.Match, _a1 error) *MatchRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MatchRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, string) ([]domain.Match, error)) *MatchRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMatchRepository creates a new instance of MatchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMatchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MatchRepository {
	mock := &MatchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
