// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/everyday-studio/ollm/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MatchUseCase is an autogenerated mock type for the MatchUseCase type
type MatchUseCase struct {
	mock.Mock
}

type MatchUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MatchUseCase) EXPECT() *MatchUseCase_Expecter {
	return &MatchUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MatchUseCase) Create(ctx context.Context, req *domain.CreateMatchRequest) (*domain.Match, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateMatchRequest) (*domain.Match, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateMatchRequest) *domain.Match); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.CreateMatchRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MatchUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MatchUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *domain.CreateMatchRequest
func (_e *MatchUseCase_Expecter) Create(ctx interface{}, req interface{}) *MatchUseCase_Create_Call {
	return &MatchUseCase_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MatchUseCase_Create_Call) Run(run func(ctx context.Context, req *domain.CreateMatchRequest)) *MatchUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.CreateMatchRequest))
	})
	return _c
}

func (_c *MatchUseCase_Create_Call) Return(_a0 *domain.Match, _a1 error) *MatchUseCase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MatchUseCase_Create_Call) RunAndReturn(run func(context.Context, *domain.CreateMatchRequest) (*domain.Match, error)) *MatchUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MatchUseCase) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MatchUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MatchUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MatchUseCase_Expecter) Delete(ctx interface{}, id interface{}) *MatchUseCase_Delete_Call {
	return &MatchUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MatchUseCase_Delete_Call) Run(run func(ctx context.Context, id string)) *MatchUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MatchUseCase_Delete_Call) Return(_a0 error) *MatchUseCase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MatchUseCase_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MatchUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MatchUseCase) GetByID(ctx context.Context, id string) (*domain.Match, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Match, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Match); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MatchUseCase_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MatchUseCase_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MatchUseCase_Expecter) GetByID(ctx interface{}, id interface{}) *MatchUseCase_GetByID_Call {
	return &MatchUseCase_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MatchUseCase_GetByID_Call) Run(run func(ctx context.Context, id string)) *MatchUseCase_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MatchUseCase_GetByID_Call) Return(_a0 *domain.Match, _a1 error) *MatchUseCase_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MatchUseCase_GetByID_Call) RunAndReturn(run func(context.Context, string) (*domain.Match, error)) *MatchUseCase_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *MatchUseCase) GetByUserID(ctx context.Context, userID string) ([]domain.Match, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []domain.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Match, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Match); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MatchUseCase_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MatchUseCase_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MatchUseCase_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MatchUseCase_GetByUserID_Call {
	return &MatchUseCase_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MatchUseCase_GetByUserID_Call) Run(run func(ctx context.Context, userID string)) *MatchUseCase_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MatchUseCase_GetByUserID_Call) Return(_a0 []domain.Match, _a1 error) *MatchUseCase_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MatchUseCase_GetByUserID_Call) RunAndReturn(run func(context.Context, string) ([]domain.Match, error)) *MatchUseCase_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMatchUseCase creates a new instance of MatchUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMatchUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MatchUseCase {
	mock := &MatchUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
