// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/everyday-studio/ollm/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// LLMService is an autogenerated mock type for the LLMService type
type LLMService struct {
	mock.Mock
}

type LLMService_Expecter struct {
	mock *mock.Mock
}

func (_m *LLMService) EXPECT() *LLMService_Expecter {
	return &LLMService_Expecter{mock: &_m.Mock}
}

// EvaluateFormatBreak provides a mock function with given fields: ctx, condition, aiContent
func (_m *LLMService) EvaluateFormatBreak(ctx context.Context, condition string, aiContent string) (bool, error) {
	ret := _m.Called(ctx, condition, aiContent)

	if len(ret) == 0 {
		panic("no return value specified for EvaluateFormatBreak")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, condition, aiContent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, condition, aiContent)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, condition, aiContent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LLMService_EvaluateFormatBreak_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvaluateFormatBreak'
type LLMService_EvaluateFormatBreak_Call struct {
	*mock.Call
}

// EvaluateFormatBreak is a helper method to define mock.On call
//   - ctx context.Context
//   - condition string
//   - aiContent string
func (_e *LLMService_Expecter) EvaluateFormatBreak(ctx interface{}, condition interface{}, aiContent interface{}) *LLMService_EvaluateFormatBreak_Call {
	return &LLMService_EvaluateFormatBreak_Call{Call: _e.mock.On("EvaluateFormatBreak", ctx, condition, aiContent)}
}

func (_c *LLMService_EvaluateFormatBreak_Call) Run(run func(ctx context.Context, condition string, aiContent string)) *LLMService_EvaluateFormatBreak_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *LLMService_EvaluateFormatBreak_Call) Return(_a0 bool, _a1 error) *LLMService_EvaluateFormatBreak_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LLMService_EvaluateFormatBreak_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *LLMService_EvaluateFormatBreak_Call {
	_c.Call.Return(run)
	return _c
}

// EvaluatePromptAdvice provides a mock function with given fields: ctx, gameRule, userContent
func (_m *LLMService) EvaluatePromptAdvice(ctx context.Context, gameRule string, userContent string) (string, error) {
	ret := _m.Called(ctx, gameRule, userContent)

	if len(ret) == 0 {
		panic("no return value specified for EvaluatePromptAdvice")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, gameRule, userContent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, gameRule, userContent)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, gameRule, userContent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LLMService_EvaluatePromptAdvice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvaluatePromptAdvice'
type LLMService_EvaluatePromptAdvice_Call struct {
	*mock.Call
}

// EvaluatePromptAdvice is a helper method to define mock.On call
//   - ctx context.Context
//   - gameRule string
//   - userContent string
func (_e *LLMService_Expecter) EvaluatePromptAdvice(ctx interface{}, gameRule interface{}, userContent interface{}) *LLMService_EvaluatePromptAdvice_Call {
	return &LLMService_EvaluatePromptAdvice_Call{Call: _e.mock.On("EvaluatePromptAdvice", ctx, gameRule, userContent)}
}

func (_c *LLMService_EvaluatePromptAdvice_Call) Run(run func(ctx context.Context, gameRule string, userContent string)) *LLMService_EvaluatePromptAdvice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *LLMService_EvaluatePromptAdvice_Call) Return(_a0 string, _a1 error) *LLMService_EvaluatePromptAdvice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LLMService_EvaluatePromptAdvice_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *LLMService_EvaluatePromptAdvice_Call {
	_c.Call.Return(run)
	return _c
}

// EvaluateWinCondition provides a mock function with given fields: ctx, judgeCondition, history
func (_m *LLMService) EvaluateWinCondition(ctx context.Context, judgeCondition string, history []domain.Message) (bool, int, int, error) {
	ret := _m.Called(ctx, judgeCondition, history)

	if len(ret) == 0 {
		panic("no return value specified for EvaluateWinCondition")
	}

	var r0 bool
	var r1 int
	var r2 int
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []domain.Message) (bool, int, int, error)); ok {
		return rf(ctx, judgeCondition, history)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []domain.Message) bool); ok {
		r0 = rf(ctx, judgeCondition, history)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []domain.Message) int); ok {
		r1 = rf(ctx, judgeCondition, history)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, []domain.Message) int); ok {
		r2 = rf(ctx, judgeCondition, history)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, []domain.Message) error); ok {
		r3 = rf(ctx, judgeCondition, history)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// LLMService_EvaluateWinCondition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvaluateWinCondition'
type LLMService_EvaluateWinCondition_Call struct {
	*mock.Call
}

// EvaluateWinCondition is a helper method to define mock.On call
//   - ctx context.Context
//   - judgeCondition string
//   - history []domain.Message
func (_e *LLMService_Expecter) EvaluateWinCondition(ctx interface{}, judgeCondition interface{}, history interface{}) *LLMService_EvaluateWinCondition_Call {
	return &LLMService_EvaluateWinCondition_Call{Call: _e.mock.On("EvaluateWinCondition", ctx, judgeCondition, history)}
}

func (_c *LLMService_EvaluateWinCondition_Call) Run(run func(ctx context.Context, judgeCondition string, history []domain.Message)) *LLMService_EvaluateWinCondition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]domain.Message))
	})
	return _c
}

func (_c *LLMService_EvaluateWinCondition_Call) Return(_a0 bool, _a1 int, _a2 int, _a3 error) *LLMService_EvaluateWinCondition_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *LLMService_EvaluateWinCondition_Call) RunAndReturn(run func(context.Context, string, []domain.Message) (bool, int, int, error)) *LLMService_EvaluateWinCondition_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateResponse provides a mock function with given fields: ctx, history
func (_m *LLMService) GenerateResponse(ctx context.Context, history []domain.Message) (string, int, int, error) {
	ret := _m.Called(ctx, history)

	if len(ret) == 0 {
		panic("no return value specified for GenerateResponse")
	}

	var r0 string
	var r1 int
	var r2 int
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.Message) (string, int, int, error)); ok {
		return rf(ctx, history)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []domain.Message) string); ok {
		r0 = rf(ctx, history)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []domain.Message) int); ok {
		r1 = rf(ctx, history)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, []domain.Message) int); ok {
		r2 = rf(ctx, history)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, []domain.Message) error); ok {
		r3 = rf(ctx, history)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// LLMService_GenerateResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateResponse'
type LLMService_GenerateResponse_Call struct {
	*mock.Call
}

// GenerateResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - history []domain.Message
func (_e *LLMService_Expecter) GenerateResponse(ctx interface{}, history interface{}) *LLMService_GenerateResponse_Call {
	return &LLMService_GenerateResponse_Call{Call: _e.mock.On("GenerateResponse", ctx, history)}
}

func (_c *LLMService_GenerateResponse_Call) Run(run func(ctx context.Context, history []domain.Message)) *LLMService_GenerateResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]domain.Message))
	})
	return _c
}

func (_c *LLMService_GenerateResponse_Call) Return(_a0 string, _a1 int, _a2 int, _a3 error) *LLMService_GenerateResponse_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *LLMService_GenerateResponse_Call) RunAndReturn(run func(context.Context, []domain.Message) (string, int, int, error)) *LLMService_GenerateResponse_Call {
	_c.Call.Return(run)
	return _c
}

// NewLLMService creates a new instance of LLMService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLLMService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LLMService {
	mock := &LLMService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
