// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/everyday-studio/ollm/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// UploadUseCase is an autogenerated mock type for the UploadUseCase type
type UploadUseCase struct {
	mock.Mock
}

type UploadUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *UploadUseCase) EXPECT() *UploadUseCase_Expecter {
	return &UploadUseCase_Expecter{mock: &_m.Mock}
}

// UploadImage provides a mock function with given fields: ctx, req
func (_m *UploadUseCase) UploadImage(ctx context.Context, req *domain.UploadImageRequest) (*domain.UploadResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UploadImage")
	}

	var r0 *domain.UploadResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UploadImageRequest) (*domain.UploadResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UploadImageRequest) *domain.UploadResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UploadResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.UploadImageRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadUseCase_UploadImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadImage'
type UploadUseCase_UploadImage_Call struct {
	*mock.Call
}

// UploadImage is a helper method to define mock.On call
//   - ctx context.Context
//   - req *domain.UploadImageRequest
func (_e *UploadUseCase_Expecter) UploadImage(ctx interface{}, req interface{}) *UploadUseCase_UploadImage_Call {
	return &UploadUseCase_UploadImage_Call{Call: _e.mock.On("UploadImage", ctx, req)}
}

func (_c *UploadUseCase_UploadImage_Call) Run(run func(ctx context.Context, req *domain.UploadImageRequest)) *UploadUseCase_UploadImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.UploadImageRequest))
	})
	return _c
}

func (_c *UploadUseCase_UploadImage_Call) Return(_a0 *domain.UploadResponse, _a1 error) *UploadUseCase_UploadImage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UploadUseCase_UploadImage_Call) RunAndReturn(run func(context.Context, *domain.UploadImageRequest) (*domain.UploadResponse, error)) *UploadUseCase_UploadImage_Call {
	_c.Call.Return(run)
	return _c
}

// NewUploadUseCase creates a new instance of UploadUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUploadUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UploadUseCase {
	mock := &UploadUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
