// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/everyday-studio/ollm/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// GameUseCase is an autogenerated mock type for the GameUseCase type
type GameUseCase struct {
	mock.Mock
}

type GameUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *GameUseCase) EXPECT() *GameUseCase_Expecter {
	return &GameUseCase_Expecter{mock: &_m.Mock}
}

// CountAll provides a mock function with given fields: ctx, filter
func (_m *GameUseCase) CountAll(ctx context.Context, filter *domain.GameFilter) (int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for CountAll")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.GameFilter) (int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.GameFilter) int); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.GameFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GameUseCase_CountAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountAll'
type GameUseCase_CountAll_Call struct {
	*mock.Call
}

// CountAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *domain.GameFilter
func (_e *GameUseCase_Expecter) CountAll(ctx interface{}, filter interface{}) *GameUseCase_CountAll_Call {
	return &GameUseCase_CountAll_Call{Call: _e.mock.On("CountAll", ctx, filter)}
}

func (_c *GameUseCase_CountAll_Call) Run(run func(ctx context.Context, filter *domain.GameFilter)) *GameUseCase_CountAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.GameFilter))
	})
	return _c
}

func (_c *GameUseCase_CountAll_Call) Return(_a0 int, _a1 error) *GameUseCase_CountAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GameUseCase_CountAll_Call) RunAndReturn(run func(context.Context, *domain.GameFilter) (int, error)) *GameUseCase_CountAll_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, req
func (_m *GameUseCase) Create(ctx context.Context, req *domain.CreateGameRequest) (*domain.Game, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateGameRequest) (*domain.Game, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateGameRequest) *domain.Game); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Game)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.CreateGameRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GameUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type GameUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *domain.CreateGameRequest
func (_e *GameUseCase_Expecter) Create(ctx interface{}, req interface{}) *GameUseCase_Create_Call {
	return &GameUseCase_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *GameUseCase_Create_Call) Run(run func(ctx context.Context, req *domain.CreateGameRequest)) *GameUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.CreateGameRequest))
	})
	return _c
}

func (_c *GameUseCase_Create_Call) Return(_a0 *domain.Game, _a1 error) *GameUseCase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GameUseCase_Create_Call) RunAndReturn(run func(context.Context, *domain.CreateGameRequest) (*domain.Game, error)) *GameUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *GameUseCase) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GameUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type GameUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *GameUseCase_Expecter) Delete(ctx interface{}, id interface{}) *GameUseCase_Delete_Call {
	return &GameUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *GameUseCase_Delete_Call) Run(run func(ctx context.Context, id string)) *GameUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *GameUseCase_Delete_Call) Return(_a0 error) *GameUseCase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GameUseCase_Delete_Call) RunAndReturn(run func(context.Context, string) error) *GameUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *GameUseCase) GetByID(ctx context.Context, id string) (*domain.Game, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Game, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Game); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Game)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GameUseCase_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type GameUseCase_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *GameUseCase_Expecter) GetByID(ctx interface{}, id interface{}) *GameUseCase_GetByID_Call {
	return &GameUseCase_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *GameUseCase_GetByID_Call) Run(run func(ctx context.Context, id string)) *GameUseCase_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *GameUseCase_GetByID_Call) Return(_a0 *domain.Game, _a1 error) *GameUseCase_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GameUseCase_GetByID_Call) RunAndReturn(run func(context.Context, string) (*domain.Game, error)) *GameUseCase_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPaginated provides a mock function with given fields: ctx, page, limit, filter
func (_m *GameUseCase) GetPaginated(ctx context.Context, page int, limit int, filter *domain.GameFilter) (*domain.PaginatedData[domain.Game], error) {
	ret := _m.Called(ctx, page, limit, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetPaginated")
	}

	var r0 *domain.PaginatedData[domain.Game]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *domain.GameFilter) (*domain.PaginatedData[domain.Game], error)); ok {
		return rf(ctx, page, limit, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *domain.GameFilter) *domain.PaginatedData[domain.Game]); ok {
		r0 = rf(ctx, page, limit, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaginatedData[domain.Game])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, *domain.GameFilter) error); ok {
		r1 = rf(ctx, page, limit, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GameUseCase_GetPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPaginated'
type GameUseCase_GetPaginated_Call struct {
	*mock.Call
}

// GetPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
//   - filter *domain.GameFilter
func (_e *GameUseCase_Expecter) GetPaginated(ctx interface{}, page interface{}, limit interface{}, filter interface{}) *GameUseCase_GetPaginated_Call {
	return &GameUseCase_GetPaginated_Call{Call: _e.mock.On("GetPaginated", ctx, page, limit, filter)}
}

func (_c *GameUseCase_GetPaginated_Call) Run(run func(ctx context.Context, page int, limit int, filter *domain.GameFilter)) *GameUseCase_GetPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(*domain.GameFilter))
	})
	return _c
}

func (_c *GameUseCase_GetPaginated_Call) Return(_a0 *domain.PaginatedData[domain.Game], _a1 error) *GameUseCase_GetPaginated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GameUseCase_GetPaginated_Call) RunAndReturn(run func(context.Context, int, int, *domain.GameFilter) (*domain.PaginatedData[domain.Game], error)) *GameUseCase_GetPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *GameUseCase) Update(ctx context.Context, id string, req *domain.UpdateGameRequest) (*domain.Game, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.UpdateGameRequest) (*domain.Game, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.UpdateGameRequest) *domain.Game); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Game)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *domain.UpdateGameRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GameUseCase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type GameUseCase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req *domain.UpdateGameRequest
func (_e *GameUseCase_Expecter) Update(ctx interface{}, id interface{}, req interface{}) *GameUseCase_Update_Call {
	return &GameUseCase_Update_Call{Call: _e.mock.On("Update", ctx, id, req)}
}

func (_c *GameUseCase_Update_Call) Run(run func(ctx context.Context, id string, req *domain.UpdateGameRequest)) *GameUseCase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*domain.UpdateGameRequest))
	})
	return _c
}

func (_c *GameUseCase_Update_Call) Return(_a0 *domain.Game, _a1 error) *GameUseCase_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GameUseCase_Update_Call) RunAndReturn(run func(context.Context, string, *domain.UpdateGameRequest) (*domain.Game, error)) *GameUseCase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewGameUseCase creates a new instance of GameUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGameUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GameUseCase {
	mock := &GameUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
